# Generated by Django 6.0.6 on 2026-06-11 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_id', models.BigIntegerField(help_text='First LinkedIn job ID to check')),
                ('current_id', models.BigIntegerField(help_text='Last ID that was checked (auto-updated)')),
                ('batch_size', models.IntegerField(default=50, help_text='How many IDs to probe per run')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scrape Config',
                'verbose_name_plural': 'Scrape Configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_id', models.BigIntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=300)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(max_length=600)),
                ('posted_date', models.CharField(blank=True, max_length=100)),
                ('employment_type', models.CharField(blank=True, max_length=100)),
                ('seniority_level', models.CharField(blank=True, max_length=100)),
                ('telegram_sent', models.BooleanField(default=False)),
                ('telegram_sent_at', models.DateTimeField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_keywords', models.ManyToManyField(blank=True, related_name='jobs', to='scrape_service.keyword')),
            ],
            options={
                'ordering': ['-linkedin_id'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('id_from', models.BigIntegerField()),
                ('id_to', models.BigIntegerField()),
                ('ids_checked', models.IntegerField(default=0)),
                ('jobs_found', models.IntegerField(default=0)),
                ('jobs_new', models.IntegerField(default=0)),
                ('alerts_sent', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='scrape_service.scrapeconfig')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
