# Generated by Django 6.0.6 on 2026-07-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, help_text='Detected from the job location', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='filter_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='is_filtered',
            field=models.BooleanField(default=False, help_text='True if this job was excluded by a country/language whitelist or blacklist rule'),
        ),
        migrations.AddField(
            model_name='job',
            name='language',
            field=models.CharField(blank=True, help_text='ISO 639-1 code detected from the job description via Hugging Face', max_length=10),
        ),
        migrations.CreateModel(
            name='CountryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='Country name as detected, e.g. "Turkey", "United States", "India"', max_length=100)),
                ('list_type', models.CharField(choices=[('whitelist', 'Whitelist (only allow)'), ('blacklist', 'Blacklist (always block)')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Country Rule',
                'verbose_name_plural': 'Country Rules',
                'ordering': ['list_type', 'country'],
                'unique_together': {('country', 'list_type')},
            },
        ),
        migrations.CreateModel(
            name='LanguageRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(help_text='ISO 639-1 code, e.g. "en", "tr"', max_length=10)),
                ('list_type', models.CharField(choices=[('whitelist', 'Whitelist (only allow)'), ('blacklist', 'Blacklist (always block)')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Language Rule',
                'verbose_name_plural': 'Language Rules',
                'ordering': ['list_type', 'language_code'],
                'unique_together': {('language_code', 'list_type')},
            },
        ),
    ]
