# Generated by Django 6.0.6 on 2026-07-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_service', '0002_job_country_job_filter_reason_job_is_filtered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code detected from the job location', max_length=10),
        ),
    ]
