# Generated by Django 6.0.6 on 2026-07-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_service', '0003_alter_job_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosterRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_name', models.CharField(blank=True, help_text='Exact poster name as it appears on LinkedIn (case-insensitive)', max_length=200)),
                ('poster_profile_url', models.URLField(blank=True, help_text='LinkedIn profile URL of the poster, e.g. https://www.linkedin.com/in/johndoe', max_length=600)),
                ('list_type', models.CharField(choices=[('whitelist', 'Whitelist (only allow)'), ('blacklist', 'Blacklist (always block)')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Poster Rule',
                'verbose_name_plural': 'Poster Rules',
                'ordering': ['list_type', 'poster_name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='poster_name',
            field=models.CharField(blank=True, help_text='Name of the job poster/recruiter, if shown', max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='poster_profile_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL of the job poster, if shown', max_length=600),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_filtered',
            field=models.BooleanField(default=False, help_text='True if this job was excluded by a country/language/poster whitelist or blacklist rule'),
        ),
    ]
