# Generated by Django 6.0.6 on 2026-07-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_service', '0004_posterrule_job_poster_name_job_poster_profile_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posterrule',
            name='poster_name',
            field=models.CharField(blank=True, help_text='Substring to match against the poster name, case-insensitive (e.g. "turing" matches "Turing Recruiting Team")', max_length=200),
        ),
    ]
