# Generated by Django 6.0.6 on 2026-07-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_service', '0005_alter_posterrule_poster_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapelog',
            name='config',
        ),
        migrations.DeleteModel(
            name='ScrapeConfig',
        ),
    ]
