# Generated by Django 6.0.6 on 2026-07-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_service', '0006_remove_scrapelog_config_delete_scrapeconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='poster_profile_url',
        ),
        migrations.RemoveField(
            model_name='posterrule',
            name='poster_profile_url',
        ),
        migrations.AlterField(
            model_name='job',
            name='poster_name',
            field=models.CharField(blank=True, help_text='Name of the job poster, or the company if no individual recruiter is shown', max_length=200),
        ),
        migrations.AlterField(
            model_name='posterrule',
            name='poster_name',
            field=models.CharField(help_text='Substring to match against the poster name, case-insensitive (e.g. "turing" matches "Turing Recruiting Team")', max_length=200),
        ),
    ]
