# Generated by Django 6.0.6 on 2026-07-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_service', '0007_remove_job_poster_profile_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countryrule',
            options={'ordering': ['country'], 'verbose_name': 'Country Rule (blacklist)', 'verbose_name_plural': 'Country Rules (blacklist)'},
        ),
        migrations.AlterModelOptions(
            name='languagerule',
            options={'ordering': ['language_code'], 'verbose_name': 'Language Rule (whitelist)', 'verbose_name_plural': 'Language Rules (whitelist)'},
        ),
        migrations.AlterModelOptions(
            name='posterrule',
            options={'ordering': ['poster_name'], 'verbose_name': 'Poster Rule (blacklist)', 'verbose_name_plural': 'Poster Rules (blacklist)'},
        ),
        migrations.AlterUniqueTogether(
            name='countryrule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='languagerule',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='posterrule',
            name='list_type',
        ),
        migrations.AlterField(
            model_name='countryrule',
            name='country',
            field=models.CharField(help_text='Country name as detected, e.g. "Turkey", "United States", "India"', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='languagerule',
            name='language_code',
            field=models.CharField(help_text='ISO 639-1 code, e.g. "en", "tr"', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='posterrule',
            name='poster_name',
            field=models.CharField(help_text='Substring to match against the poster name, case-insensitive (e.g. "turing" matches "Turing Recruiting Team")', max_length=200, unique=True),
        ),
        migrations.RemoveField(
            model_name='countryrule',
            name='list_type',
        ),
        migrations.RemoveField(
            model_name='languagerule',
            name='list_type',
        ),
    ]
