# Generated by Django 6.0.6 on 2026-07-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_service', '0008_alter_countryrule_options_alter_languagerule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Title Keyword',
                'verbose_name_plural': 'Title Keywords',
                'ordering': ['word'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='matched_title_keywords',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='scrape_service.titlekeyword'),
        ),
    ]
